meal_plans/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from meal_plans.views import (
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanUpdateView,
    MealPlanDetailView,
    MealPlanListView,
)

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("", MealPlanListView.as_view(), name="meal_plans_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plans_detail"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plans_delete",
    ),
    path("new/", MealPlanCreateView.as_view(), name="meal_plans_new"),
    path(
        "<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plans_edit"
    ),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

# In the scrumptious/urls.py file, we need to add the login view from
# the built-in authentication views that come with Django.
# Adding the login page


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models

# Create your models here.
from django.conf import settings


# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField(
        auto_now_add=True,
    )
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, null=True)
    recipes = models.ManyToManyField(
        "recipes.Recipe", related_name="meal_plans", blank=True
    )

    def __str__(self):
        return self.name

meal_plans/views.py
from django.shortcuts import redirect, render  # Which one should I Use and Why?
from django.urls import (
    reverse_lazy,
)  # what is reverse_lazy and why do we need to import it?

# Normally the Url pattern is taking you to the Views, but the reason why its called reverse_lazy is
# so that reverse_lazy is taking you back to the URL pattern.
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# Why is it generic.*** and not just django.views?
# what makes generic function so important? Generic is a django library that contains generic class views
# Create your views here.


from meal_plans.models import MealPlan

#  Then, you need to apply it to every create, update, and delete view.
#  Here's an example of how that's done.
#  class RecipeCreateView(LoginRequiredMixin, CreateView):
#  model = Recipe
#  template_name = "recipes/new.html"
#  fields = ["name", "author", "description", "image"]
#  success_url = reverse_lazy("recipes_list")


class MealPlanListView(ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 2


# def get_queryset(self):
# return MealPlan.objects.filter(owner=self.request.user)
# The error is telling you that request.user is an anonymous user.
# That means that they are not logged in, so it doesn't make sense
# to try to filter with filter(user=request.user).
# The easiest fix is to use the login_required decorator, to make
# sure that only logged-in users can access the view.


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "owner", "recipes"]
    success_url: reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        MealPlan = form.save(commit=False)
        MealPlan.instance.owner = self.request.user
        MealPlan.save()
        form.save_m2m()
        # self.request.user(in a class view. the self is a class instance.) or request.user(in a function based view)
        # when the user makes a request to the website.
        return redirect(
            "meal_plans_detail", pk=plan.id
        )  # super().form_valid(form)


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plan/delete.html"
    success_url = reverse_lazy("meal_plans_list")


# def get_queryset(self):
# return MealPlan.objects.filter(owner=self.request.user)
# The error is telling you that request.user is an anonymous user.
# That means that they are not logged in, so it doesn't make sense
# to try to filter with filter(user=request.user).
# The easiest fix is to use the login_required decorator, to make
# sure that only logged-in users can access the view.


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plan/detail.html"
    # What does the code below means!!!!!

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()
        return context


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "recipes/edit.html"
    fields = ["name", "date", "owner", "recipes"]
    success_url = reverse_lazy("meal_plans_list")


# def get_queryset(self):
# return MealPlan.objects.filter(owner=self.request.user)
# The error is telling you that request.user is an anonymous user.
# That means that they are not logged in, so it doesn't make sense
# to try to filter with filter(user=request.user).
# The easiest fix is to use the login_required decorator, to make
# sure that only logged-in users can access the view.

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}


<main>
  <div class="delete-form">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ recipe }}"?</p>
      {{ form.as_p }}
      <div>
        <button class="button">Delete</button>
      </div>
    </form>
  </div>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'meal_plans/base.html' %}

{% load static %}

{% load markdownify %}

{% block content %}

<main class="recipe-detail">
  <div>
    <a href="{% url 'meal_plans_edit' recipe.id %}">Edit</a>
    <a href="{% url 'meal_plans_delete' recipe.id %}">Delete</a>
  </div>
  {% if recipe.image %}
  <img src="{{ recipe.image }}" class="pull-right" />
  {% endif %}
  <h1>{{ recipe.name }}</h1>
  <h2>by: {{ recipe.author | default_if_none:"Unknown" }}</h2>
  <p>Created on {{ recipe.created }} | Updated on {{ recipe.updated }}</p>
  <form method="post" action="{% url 'recipe_rating' recipe.id %}">
    {% csrf_token %}
    <div class="rating-form-grid">
      {{ rating_form.as_p }}
      <button class="button">Rate</button>
    </div>
  </form>
  <p>Tags: {% for tag in recipe.tags.all %}{{ tag.word }} {% endfor %}</p>
  {{ recipe.description | markdownify }}
  <h2>Ingredients</h2>
  <table>
    <thead>
      <tr>
        <th colspan="2">Amount</th>
        <th>Food item</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredient in recipe.ingredients.all %}
      <tr>
        <td>{{ ingredient.amount }}</td>
        <td>{{ ingredient.measure.name }}</td>
        <td>{{ ingredient.food.name }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Steps</h2>
  <ol>
    {% for step in recipe.steps.all %}
    <li>{{ step.directions }}</li>
    {% endfor %}
  </ol>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}

<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{% block pagination %}


<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; First</a>
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock pagination %}


{% block content %}

<main class="recipe-grid">
  {% for mealplan in mealplan_list %}
    <div class="recipe-card">
      <h2 class="recipe-card-title">
        <a href="{% url 'meal_plans_detail' mealplan.pk %}">{{ mealplan.name }}</a>
      </h2>
      <p class="recipe-card-date">{{ recipe.updated }}</p>
      {% for recipe in mealplan.recipes.all %}
      <p>
      <a href= "{% url "recipe_detail" recipe.pk %}">
        {{recipe.name}}</a></p>
      </div>
    {% endfor %}
    </div>
  {% endfor %}

  </main>
  </body>
  {% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'meal_base.html' %}

{% block content %}


<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}